#!/bin/bash
# Script to run dx8gl sample tests

echo "=== Running dx8gl Sample Tests ==="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Change to build directory
SCRIPT_DIR="$(dirname "$0")"
BUILD_DIR="$SCRIPT_DIR/../../../build"
if [ ! -d "$BUILD_DIR" ]; then
    echo -e "${RED}Build directory not found: $BUILD_DIR${NC}"
    exit 1
fi

# Make sure samples are built
echo "Building dx8gl samples..."
cmake --build "$BUILD_DIR" --target dx8gl_clear_test dx8gl_triangle dx8gl_textured_cube \
    dx8gl_lighting_test dx8gl_multitexture_test dx8gl_alpha_blend_test \
    dx8gl_state_changes_test dx8gl_vertex_shader_test dx8gl_shader_assembly_test \
    dx8gl_complex_vertex_shader_test dx8gl_shader_translation_test \
    dx8gl_pixel_shader_test dx8gl_shader_modifiers_test \
    dx8gl_bytecode_assembler_test dx8gl_constant_batching_test \
    dx8gl_test_shader_features dx8gl_shader_test \
    test_backend_selection test_framebuffer_correctness -j4

if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to build samples${NC}"
    exit 1
fi

# Run tests using ctest
echo -e "\n${YELLOW}Running tests with CTest...${NC}"
cd "$BUILD_DIR/lib/dx8gl/samples" || exit 1

# Run all tests with verbose output
ctest --output-on-failure --timeout 30

TEST_RESULT=$?

# Summary
echo -e "\n=== Test Summary ==="
if [ $TEST_RESULT -eq 0 ]; then
    echo -e "${GREEN}All tests PASSED!${NC}"
    
    # Check for generated PPM files
    echo -e "\nChecking for generated output files..."
    PPM_COUNT=$(find . -name "*.ppm" -type f 2>/dev/null | wc -l)
    echo "Found $PPM_COUNT PPM image files generated by tests"
    
    if [ $PPM_COUNT -gt 0 ]; then
        echo "Sample outputs:"
        find . -name "*.ppm" -type f 2>/dev/null | head -5
    fi
else
    echo -e "${RED}Some tests FAILED!${NC}"
    echo "Run 'ctest --rerun-failed --output-on-failure' to see detailed errors"
fi

# Run shader feature tests separately for detailed output
echo -e "\n${YELLOW}Running shader feature tests...${NC}"
if [ -f "./dx8gl_test_shader_features" ]; then
    LD_LIBRARY_PATH="../:$LD_LIBRARY_PATH" ./dx8gl_test_shader_features
else
    echo -e "${RED}Shader feature test not found${NC}"
fi

# Run shader translation and cache tests
echo -e "\n${YELLOW}Running shader translation and cache tests...${NC}"
if [ -f "$BUILD_DIR/ext/dx8gl/samples/shader_test/dx8gl_shader_test" ]; then
    LD_LIBRARY_PATH="$BUILD_DIR/ext/dx8gl:$LD_LIBRARY_PATH" "$BUILD_DIR/ext/dx8gl/samples/shader_test/dx8gl_shader_test"
    SHADER_TEST_RESULT=$?
    if [ $SHADER_TEST_RESULT -eq 0 ]; then
        echo -e "${GREEN}Shader translation tests PASSED${NC}"
    else
        echo -e "${RED}Shader translation tests FAILED${NC}"
        TEST_RESULT=1
    fi
else
    echo -e "${RED}Shader translation test not found${NC}"
fi

# Run backend selection tests
echo -e "\n${YELLOW}Running backend selection tests...${NC}"
if [ -f "$BUILD_DIR/ext/dx8gl/test/test_backend_selection" ]; then
    LD_LIBRARY_PATH="$BUILD_DIR/ext/dx8gl:$BUILD_DIR/llvm-install/lib:$BUILD_DIR/mesa-install/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" \
    "$BUILD_DIR/ext/dx8gl/test/test_backend_selection"
    BACKEND_TEST_RESULT=$?
    if [ $BACKEND_TEST_RESULT -eq 0 ]; then
        echo -e "${GREEN}Backend selection tests PASSED${NC}"
    else
        echo -e "${RED}Backend selection tests FAILED${NC}"
        TEST_RESULT=1
    fi
else
    echo -e "${RED}Backend selection test not found${NC}"
fi

# Run framebuffer correctness tests
echo -e "\n${YELLOW}Running framebuffer correctness tests...${NC}"
if [ -f "$BUILD_DIR/ext/dx8gl/test/test_framebuffer_correctness" ]; then
    LD_LIBRARY_PATH="$BUILD_DIR/ext/dx8gl:$BUILD_DIR/llvm-install/lib:$BUILD_DIR/mesa-install/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" \
    "$BUILD_DIR/ext/dx8gl/test/test_framebuffer_correctness"
    FRAMEBUFFER_TEST_RESULT=$?
    if [ $FRAMEBUFFER_TEST_RESULT -eq 0 ]; then
        echo -e "${GREEN}Framebuffer correctness tests PASSED${NC}"
    else
        echo -e "${RED}Framebuffer correctness tests FAILED${NC}"
        TEST_RESULT=1
    fi
else
    echo -e "${RED}Framebuffer correctness test not found${NC}"
fi

exit $TEST_RESULT