
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "u_gles/CMakeLists.txt:60 (check_include_file)"
    checks:
      - "Looking for threads.h"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-V1ThWk"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-V1ThWk"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_THREADS_H"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-V1ThWk'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_3ff4d/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_3ff4d.dir/build.make CMakeFiles/cmTC_3ff4d.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-V1ThWk'
        Building C object CMakeFiles/cmTC_3ff4d.dir/CheckIncludeFile.c.o
        /usr/bin/emcc   -std=gnu11 -MD -MT CMakeFiles/cmTC_3ff4d.dir/CheckIncludeFile.c.o -MF CMakeFiles/cmTC_3ff4d.dir/CheckIncludeFile.c.o.d -o CMakeFiles/cmTC_3ff4d.dir/CheckIncludeFile.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-V1ThWk/CheckIncludeFile.c
        Linking C executable cmTC_3ff4d.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3ff4d.dir/link.txt --verbose=1
        /usr/bin/emcc @CMakeFiles/cmTC_3ff4d.dir/objects1.rsp -o cmTC_3ff4d.js 
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-V1ThWk'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckFunctionExists.cmake:86 (try_compile)"
      - "u_gles/CMakeLists.txt:65 (check_function_exists)"
    checks:
      - "Looking for fmemopen"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-3SvVa3"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-3SvVa3"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_FMEMOPEN"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-3SvVa3'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_f67d2/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_f67d2.dir/build.make CMakeFiles/cmTC_f67d2.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-3SvVa3'
        Building C object CMakeFiles/cmTC_f67d2.dir/CheckFunctionExists.c.o
        /usr/bin/emcc   -DCHECK_FUNCTION_EXISTS=fmemopen -std=gnu11 -MD -MT CMakeFiles/cmTC_f67d2.dir/CheckFunctionExists.c.o -MF CMakeFiles/cmTC_f67d2.dir/CheckFunctionExists.c.o.d -o CMakeFiles/cmTC_f67d2.dir/CheckFunctionExists.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-3SvVa3/CheckFunctionExists.c
        Linking C executable cmTC_f67d2.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f67d2.dir/link.txt --verbose=1
        /usr/bin/emcc  -DCHECK_FUNCTION_EXISTS=fmemopen @CMakeFiles/cmTC_f67d2.dir/objects1.rsp -o cmTC_f67d2.js 
        wasm-ld-15: warning: function signature mismatch: fmemopen
        >>> defined as () -> i32 in CMakeFiles/cmTC_f67d2.dir/CheckFunctionExists.c.o
        >>> defined as (i32, i32, i32) -> i32 in /usr/share/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-debug.a(fmemopen.o)
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-3SvVa3'
        
      exitCode: 0

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "u_gles/CMakeLists.txt:60 (check_include_file)"
    checks:
      - "Looking for threads.h"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-disn8A"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-disn8A"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_THREADS_H"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-disn8A'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_a5b09/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_a5b09.dir/build.make CMakeFiles/cmTC_a5b09.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-disn8A'
        Building C object CMakeFiles/cmTC_a5b09.dir/CheckIncludeFile.c.o
        /usr/bin/emcc   -std=gnu11 -MD -MT CMakeFiles/cmTC_a5b09.dir/CheckIncludeFile.c.o -MF CMakeFiles/cmTC_a5b09.dir/CheckIncludeFile.c.o.d -o CMakeFiles/cmTC_a5b09.dir/CheckIncludeFile.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-disn8A/CheckIncludeFile.c
        Linking C executable cmTC_a5b09.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a5b09.dir/link.txt --verbose=1
        /usr/bin/emcc @CMakeFiles/cmTC_a5b09.dir/objects1.rsp -o cmTC_a5b09.js 
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-disn8A'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckFunctionExists.cmake:86 (try_compile)"
      - "u_gles/CMakeLists.txt:65 (check_function_exists)"
    checks:
      - "Looking for fmemopen"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-YdjiqY"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-YdjiqY"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_FMEMOPEN"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-YdjiqY'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_4ec73/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_4ec73.dir/build.make CMakeFiles/cmTC_4ec73.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-YdjiqY'
        Building C object CMakeFiles/cmTC_4ec73.dir/CheckFunctionExists.c.o
        /usr/bin/emcc   -DCHECK_FUNCTION_EXISTS=fmemopen -std=gnu11 -MD -MT CMakeFiles/cmTC_4ec73.dir/CheckFunctionExists.c.o -MF CMakeFiles/cmTC_4ec73.dir/CheckFunctionExists.c.o.d -o CMakeFiles/cmTC_4ec73.dir/CheckFunctionExists.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-YdjiqY/CheckFunctionExists.c
        Linking C executable cmTC_4ec73.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4ec73.dir/link.txt --verbose=1
        /usr/bin/emcc  -DCHECK_FUNCTION_EXISTS=fmemopen @CMakeFiles/cmTC_4ec73.dir/objects1.rsp -o cmTC_4ec73.js 
        wasm-ld-15: warning: function signature mismatch: fmemopen
        >>> defined as () -> i32 in CMakeFiles/cmTC_4ec73.dir/CheckFunctionExists.c.o
        >>> defined as (i32, i32, i32) -> i32 in /usr/share/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-debug.a(fmemopen.o)
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-YdjiqY'
        
      exitCode: 0

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "u_gles/CMakeLists.txt:60 (check_include_file)"
    checks:
      - "Looking for threads.h"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-Nrh4tC"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-Nrh4tC"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_THREADS_H"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-Nrh4tC'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_d5ea8/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_d5ea8.dir/build.make CMakeFiles/cmTC_d5ea8.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-Nrh4tC'
        Building C object CMakeFiles/cmTC_d5ea8.dir/CheckIncludeFile.c.o
        /usr/bin/emcc   -std=gnu11 -MD -MT CMakeFiles/cmTC_d5ea8.dir/CheckIncludeFile.c.o -MF CMakeFiles/cmTC_d5ea8.dir/CheckIncludeFile.c.o.d -o CMakeFiles/cmTC_d5ea8.dir/CheckIncludeFile.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-Nrh4tC/CheckIncludeFile.c
        Linking C executable cmTC_d5ea8.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d5ea8.dir/link.txt --verbose=1
        /usr/bin/emcc @CMakeFiles/cmTC_d5ea8.dir/objects1.rsp -o cmTC_d5ea8.js 
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-Nrh4tC'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckFunctionExists.cmake:86 (try_compile)"
      - "u_gles/CMakeLists.txt:65 (check_function_exists)"
    checks:
      - "Looking for fmemopen"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-z6jKOj"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-z6jKOj"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_FMEMOPEN"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-z6jKOj'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_142c3/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_142c3.dir/build.make CMakeFiles/cmTC_142c3.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-z6jKOj'
        Building C object CMakeFiles/cmTC_142c3.dir/CheckFunctionExists.c.o
        /usr/bin/emcc   -DCHECK_FUNCTION_EXISTS=fmemopen -std=gnu11 -MD -MT CMakeFiles/cmTC_142c3.dir/CheckFunctionExists.c.o -MF CMakeFiles/cmTC_142c3.dir/CheckFunctionExists.c.o.d -o CMakeFiles/cmTC_142c3.dir/CheckFunctionExists.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-z6jKOj/CheckFunctionExists.c
        Linking C executable cmTC_142c3.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_142c3.dir/link.txt --verbose=1
        /usr/bin/emcc  -DCHECK_FUNCTION_EXISTS=fmemopen @CMakeFiles/cmTC_142c3.dir/objects1.rsp -o cmTC_142c3.js 
        wasm-ld-15: warning: function signature mismatch: fmemopen
        >>> defined as () -> i32 in CMakeFiles/cmTC_142c3.dir/CheckFunctionExists.c.o
        >>> defined as (i32, i32, i32) -> i32 in /usr/share/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-debug.a(fmemopen.o)
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-z6jKOj'
        
      exitCode: 0

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CheckIncludeFile.cmake:90 (try_compile)"
      - "u_gles/CMakeLists.txt:60 (check_include_file)"
    checks:
      - "Looking for threads.h"
    directories:
      source: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-bXWUWY"
      binary: "/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-bXWUWY"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules;/usr/share/emscripten/cmake/Modules"
    buildResult:
      variable: "HAVE_THREADS_H"
      cached: true
      stdout: |
        Change Dir: '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-bXWUWY'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_8b70e/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_8b70e.dir/build.make CMakeFiles/cmTC_8b70e.dir/build
        gmake[1]: Entering directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-bXWUWY'
        Building C object CMakeFiles/cmTC_8b70e.dir/CheckIncludeFile.c.o
        /usr/bin/emcc   -std=gnu11 -MD -MT CMakeFiles/cmTC_8b70e.dir/CheckIncludeFile.c.o -MF CMakeFiles/cmTC_8b70e.dir/CheckIncludeFile.c.o.d -o CMakeFiles/cmTC_8b70e.dir/CheckIncludeFile.c.o -c /home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-bXWUWY/CheckIncludeFile.c
        Linking C executable cmTC_8b70e.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8b70e.dir/link.txt --verbose=1
        /usr/bin/emcc @CMakeFiles/cmTC_8b70e.dir/objects1.rsp -o cmTC_8b70e.js 
        gmake[1]: Leaving directory '/home/djs/CnC_Generals_Zero_Hour/lib/dx8gl/CMakeFiles/CMakeScratch/TryCompile-bXWUWY'
        
      exitCode: 0
